server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://13.57.2.118:3306/mytest
        username: admin
        password: Admin123456!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      # Enable template caching.
      #缓存 正式环境true
      #thymeleaf.cache: true
      # 本地测试
      thymeleaf.cache: false
      # Check that the templates location exists.
      thymeleaf.check-template-location: true
      # Content-Type value.
      thymeleaf.content-type: text/html
      # Enable MVC Thymeleaf view resolution.
      thymeleaf.enabled: true
      # Template encoding.
      thymeleaf.encoding: UTF-8
      # Comma-separated list of view names that should be excluded from resolution.
      thymeleaf.excluded-view-names:
      # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
      thymeleaf.mode: HTML5
      # Prefix that gets prepended to view names when building a URL.
      thymeleaf.prefix: classpath:/templates/
      # Suffix that gets appended to view names when building a URL.
      thymeleaf.suffix: .html
      thymeleaf.template-resolver-order: # Order of the template resolver in the chain.
      thymeleaf.view-names:
      # Comma-separated list of view names that can be resolved.
    mvc:
      # 静态文件请求匹配方式
      static-path-pattern: /static/**
      # 修改默认的静态寻址资源目录
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#logging:
#  level:
#  com.onepro.custom.mapper: DEBUG